within Tests;
model All "Complete Modelica assertion suite"
  Tests.LinearAlgebraTests linearAlgebra;
  Tests.LieGroupsTests lieGroupsSmoke;
  Tests.LieGroupTests.Suite lieGroups;
  Tests.EstimationTests estimation;
  Tests.StrapdownESKFTests strapdownESKF;
  Tests.StrapdownUKFTests strapdownUKF;
  Tests.StrapdownPreintegrationTests strapdownPreintegration;
  Tests.OpticalFlowPlaneTests opticalFlowPlane;
  Tests.SensorCorrectionTests sensorCorrections;
  Tests.EstimatorHealthTests estimatorHealth;
  Tests.EstimatorHardeningTests estimatorHardening;
  Tests.VerificationTests verification;
  Tests.PlanningTests planning;
  Tests.BezierTests bezier;
  Tests.GeodesyTests geodesy;
  Tests.MultirotorInnerLoopTests multirotorInnerLoop;
  Tests.Cubs2EstimatorTests cubs2Estimator;
  Tests.DynamicsTests.Suite dynamics;
  annotation(experiment(StartTime=0.0, StopTime=1.0, Tolerance=1.0e-8, Interval=0.001));
end All;
