within;

// SPDX-License-Identifier: BSD-3-Clause
// Copyright (c) 2012 - 2025, PX4 Development Team. All rights reserved.
// Transcribed from PX4-Autopilot at commit
// bd62df5e3ac3f3f4a07da4518062a922492adb6c. The upstream copyright notice,
// the three BSD-3-Clause conditions, and the warranty disclaimer are retained
// verbatim in Ekf2/LICENSE, as condition 1 of that license requires.

package Ekf2
  "Modelica reimplementation of the PX4 EKF2 error-state Kalman filter for benchmark comparison"

  annotation(
    Documentation(info = "<html>
<h4>Ekf2: a Modelica reimplementation of PX4 EKF2</h4>
<p>
This package is a from-scratch reimplementation of the mathematics of the PX4
EKF2 error-state Kalman filter, written so the estimator benchmark can compare
pure filter mathematics through a single compiler pipeline. It is not original
estimator design: it deliberately preserves EKF2's error-state definition, its
24 degree-of-freedom tangent layout, its fusion order, its innovation gating,
and its covariance update forms. The intent is that a reader recognises this as
the PX4 EKF2 math and not a new filter.
</p>

<h4>Provenance and license</h4>
<p>
The reference implementation is the ECL EKF that ships as the ekf2 module of
PX4-Autopilot (originally PX4/ecl, primary author Paul Riseborough). The math in
this package was read from:
</p>
<ul>
<li>Project: PX4-Autopilot, module <code>src/modules/ekf2/EKF</code></li>
<li>Upstream repository: https://github.com/PX4/PX4-Autopilot</li>
<li>Commit read from: <code>bd62df5e3ac3f3f4a07da4518062a922492adb6c</code></li>
<li>Upstream license: BSD-3-Clause, Copyright (c) 2015-2023 PX4 Development Team
    (covariance derivation Copyright (c) 2022-2023 PX4 Development Team)</li>
</ul>
<p>
This directory is therefore BSD-3-Clause, not Apache-2.0. It is the only
exception in this repository; everything outside <code>Ekf2/</code> is
Apache-2.0 under the root <code>LICENSE</code>.
</p>
<p>
BSD-3-Clause condition 1 requires that a redistribution of source code retain
the copyright notice, the list of conditions, and the disclaimer. They are
retained verbatim, not paraphrased, in <code>Ekf2/LICENSE</code>, which also
carries the upstream repository license, the per-file copyright lines of every
transcribed source, and the transcription manifest. Every
<code>Ekf2/*.mo</code> file additionally carries an
<code>SPDX-License-Identifier: BSD-3-Clause</code> header and the copyright
line of the source it transcribes. The conditions themselves, reproduced from
the upstream file headers:
</p>
<blockquote>
<p>
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
</p>
<p>
1. Redistributions of source code must retain the above copyright notice, this
list of conditions and the following disclaimer.<br/>
2. Redistributions in binary form must reproduce the above copyright notice,
this list of conditions and the following disclaimer in the documentation
and/or other materials provided with the distribution.<br/>
3. Neither the name PX4 nor the names of its contributors may be used to
endorse or promote products derived from this software without specific prior
written permission.
</p>
<p>
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
</p>
</blockquote>
<p>
No PX4 endorsement is claimed. Every upstream file and function transcribed is
cited in the per-function documentation.
</p>

<h4>Covariance mathematics: SymForce-derived</h4>
<p>
The covariance-prediction expressions in <code>Ekf2.PredictCovariance</code> are
a transcription of the header
<code>src/modules/ekf2/EKF/python/ekf_derivation/generated/predict_covariance.h</code>,
which each generated file's own banner records as autogenerated by SymForce from
the symbolic derivation in
<code>src/modules/ekf2/EKF/python/ekf_derivation/derivation.py</code>. The
transcription preserves the generated expression tree (the 144 intermediate
terms and the 300 upper-triangular output assignments) statement for statement.
</p>

<h4>References</h4>
<p>The following are the mathematical lineage of the transcribed code. Titles
and venues were verified against the sources named, not quoted from memory.</p>
<ol>
<li>PX4 EKF2 module and ECL EKF derivation, PX4-Autopilot commit
    <code>bd62df5e3ac3f3f4a07da4518062a922492adb6c</code>,
    <code>src/modules/ekf2/EKF</code> (C++ sources and
    <code>python/ekf_derivation/derivation.py</code>). Filter background and a
    reference list are provided by the module documentation
    (<code>EKF/documentation/</code>, author Paul Riseborough), verified in
    <code>EKF/documentation/readme.txt</code>.</li>
<li>Sola, Joan. \"Quaternion kinematics for the error-state Kalman filter.\"
    arXiv preprint arXiv:1711.02508 (2017). Cited by the EKF2 derivation as its
    error-state formulation basis, verified in
    <code>derivation.py</code> line 35.</li>
<li>Martiros, Hayk, et al. \"SymForce: Symbolic Computation and Code Generation
    for Robotics.\" Proceedings of Robotics: Science and Systems (RSS), 2022.
    arXiv:2204.07889. SymForce is the symbolic code generator that produced the
    covariance headers transcribed here, verified from each generated header's
    autogeneration banner and the <code>symforce</code> imports in
    <code>derivation.py</code>.</li>
</ol>

<h4>Frames and conventions</h4>
<p>
This package keeps EKF2's own conventions rather than the repository's ENU/FLU
convention, because the point of the port is fidelity to EKF2: world frame is
North-East-Down (NED), body frame is Forward-Right-Down (FRD), the nominal
attitude quaternion is Hamilton scalar-first mapping body to earth, and the
attitude error is a left (global, NED-frame) multiplicative perturbation. The full
state map is the <code>state</code> input comment on
<code>Ekf2.PredictCovariance</code>; the repository's own estimator uses the
opposite (right, body-frame) perturbation on SE_2(3), documented at
<code>Estimation.StrapdownINS.ESKF</code>.
</p>
</html>"));
end Ekf2;
